name: complex

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
          

  windows:
    runs-on: windows-latest
    steps:
    - run: date

  macos:
    runs-on: macos-latest
    steps:
    - run: date

  dependfour:
    needs: [windows, macos]
    runs-on: macos-latest
    steps:
    - run: date
  
